/*

 FILED.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\mura\Desktop\hobby\GB\gbtd22\Testtile.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define FieldTileLabelWidth 32
#define FieldTileLabelHeight 32
#define FieldTileLabelBank 0

extern unsigned char FieldTileLabel[];

/* End of FILED.H */
